<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Puneet-Dell" ignored="0" name="nopCommerce_V1 Test1" tests="6" failures="3" timestamp="19 Feb 2019 17:24:56 GMT" time="82.093" errors="0">
  <testcase name="LoginTest" time="15.479" classname="com.nopCommerce_V1.testcases.LoginTest001"/>
  <testcase name="logintest" time="12.206" classname="com.nopCommerce_V1.testcases.TC_LoginDatadriven"/>
  <testcase name="logintest" time="2.452" classname="com.nopCommerce_V1.testcases.TC_LoginDatadriven">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopCommerce_V1.testcases.TC_LoginDatadriven.logintest(TC_LoginDatadriven.java:50)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- logintest -->
  <testcase name="logintest" time="2.718" classname="com.nopCommerce_V1.testcases.TC_LoginDatadriven">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopCommerce_V1.testcases.TC_LoginDatadriven.logintest(TC_LoginDatadriven.java:50)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- logintest -->
  <testcase name="logintest" time="2.776" classname="com.nopCommerce_V1.testcases.TC_LoginDatadriven">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopCommerce_V1.testcases.TC_LoginDatadriven.logintest(TC_LoginDatadriven.java:50)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- logintest -->
  <testcase name="addNewCustomer" time="26.357" classname="com.nopCommerce_V1.testcases.Addcust003"/>
</testsuite> <!-- nopCommerce_V1 Test1 -->
